#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xffe8;
constexpr uint24_t FX_DATA_BYTES = 5929;

constexpr uint24_t STARFIGHTER = 0x000000;
constexpr uint24_t STARFIGHTERMask = 0x00044C;
constexpr uint24_t speaker1 = 0x0005BA;
constexpr uint24_t speaker1Mask = 0x00067C;
constexpr uint24_t sound1 = 0x0006BC;
constexpr uint24_t sound1Mask = 0x0006E8;
constexpr uint24_t flash = 0x0006F6;
constexpr uint24_t flashMask = 0x000701;
constexpr uint24_t shot = 0x000704;
constexpr uint24_t shotMask = 0x00071B;
constexpr uint24_t heart = 0x000722;
constexpr uint24_t heartMask = 0x000739;
constexpr uint24_t powerUp = 0x000740;
constexpr uint24_t powerUpMask = 0x00075A;
constexpr uint24_t bomb1 = 0x000762;
constexpr uint24_t bomb1Mask = 0x0007B2;
constexpr uint24_t GAMEOVER = 0x0007CC;
constexpr uint24_t GAMEOVERMask = 0x00093C;
constexpr uint24_t gameoverMask = 0x0009B6;
constexpr uint24_t player = 0x0009E3;
constexpr uint24_t playerMask = 0x000A45;
constexpr uint24_t playerUp = 0x000A65;
constexpr uint24_t playerUpMask = 0x000AC7;
constexpr uint24_t playerDown = 0x000AE7;
constexpr uint24_t playerDownMask = 0x000B49;
constexpr uint24_t enemy = 0x000B69;
constexpr uint24_t enemyMask = 0x000BCB;
constexpr uint24_t tank = 0x000BEB;
constexpr uint24_t tankMask = 0x000C4D;
constexpr uint24_t swerver = 0x000C6D;
constexpr uint24_t swerverMask = 0x000CC9;
constexpr uint24_t ring = 0x000CE7;
constexpr uint24_t ringMask = 0x000D49;
constexpr uint24_t explode1 = 0x000D69;
constexpr uint24_t explode1Mask = 0x000DCB;
constexpr uint24_t explode2 = 0x000DEB;
constexpr uint24_t explode2Mask = 0x000E4D;
constexpr uint24_t explode3 = 0x000E6D;
constexpr uint24_t explode3Mask = 0x000ECF;
constexpr uint24_t plasma1 = 0x000EEF;
constexpr uint24_t plasmaMask = 0x000F06;
constexpr uint24_t sigma = 0x000F0D;
constexpr uint24_t sigmaMask = 0x000F24;
constexpr uint24_t boss = 0x000F2B;
constexpr uint24_t bossMask = 0x0010AD;
constexpr uint24_t end = 0x00112D;
constexpr uint24_t endMask = 0x00118F;
constexpr uint24_t endScreen = 0x0011AF;
constexpr uint24_t endScreenMask = 0x0015CB;
